/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardBudgetsRouteImport } from './routes/dashboard/budgets'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard/goals'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard/insights'
import { Route as DashboardRecurringRouteImport } from './routes/dashboard/recurring'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBudgetsRoute = DashboardBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecurringRoute = DashboardRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/budgets': typeof DashboardBudgetsRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/recurring': typeof DashboardRecurringRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/budgets': typeof DashboardBudgetsRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/recurring': typeof DashboardRecurringRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/budgets': typeof DashboardBudgetsRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/recurring': typeof DashboardRecurringRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/accounts'
    | '/dashboard/budgets'
    | '/dashboard/goals'
    | '/dashboard/insights'
    | '/dashboard/recurring'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/dashboard/accounts'
    | '/dashboard/budgets'
    | '/dashboard/goals'
    | '/dashboard/insights'
    | '/dashboard/recurring'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/reset-password'
    | '/dashboard/accounts'
    | '/dashboard/budgets'
    | '/dashboard/goals'
    | '/dashboard/insights'
    | '/dashboard/recurring'
    | '/dashboard/settings'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/budgets': {
      id: '/dashboard/budgets'
      path: '/budgets'
      fullPath: '/dashboard/budgets'
      preLoaderRoute: typeof DashboardBudgetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recurring': {
      id: '/dashboard/recurring'
      path: '/recurring'
      fullPath: '/dashboard/recurring'
      preLoaderRoute: typeof DashboardRecurringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardBudgetsRoute: typeof DashboardBudgetsRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardRecurringRoute: typeof DashboardRecurringRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardBudgetsRoute: DashboardBudgetsRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardRecurringRoute: DashboardRecurringRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
